@startuml
'https://plantuml.com/sequence-diagram

participant ":GameObject" as gameObject
participant ":InteractionType" as InteractionType
participant ":HelpObject" as HelpObject

[->gameObject : selectInteraction(theInteractionType)
activate gameObject

gameObject -> InteractionType **: current = create(theInteractionType)
activate  InteractionType
gameObject -> InteractionType : getOptions(current)
InteractionType --> gameObject : theOptions = current.options
'deactivate InteractionType
note right : options is a vector-member in InteractionType
gameObject -> HelpObject : theFormattedOptions = format(theOptions)
activate HelpObject
gameObject -->[ : <Map>(theFormattedOptions, theOptions)
deactivate HelpObject
deactivate gameObject


'[<--someObject : interaction options
'activate someObject

@enduml