@startuml
'https://plantuml.com/sequence-diagram

'User selects an object to interact with, system then
'returns what interactions are available for that object.
participant ":GameElement" as gameElement
'participant ":Scene" as scene
participant ":GameObject" as gameObject

[->gameElement : selectObject(theGameObject)
activate gameElement

gameElement -> gameObject : theInteractions = getAvailableInteractions(theGameObject)
activate gameObject
deactivate gameObject


[<--gameElement : theInteractions
deactivate gameElement


@enduml