@startuml
'https://plantuml.com/sequence-diagram

'participant "currentInteraction:InteractionType" as currInt

[->game : startInteraction()
game->controller : delegate
controller->someclass : dothis
'activate currInt


'deactivate currInt


'[<--someObject : result of interaction
'activate someObject
@enduml